[build]
builder = "dockercompose"

[deploy]
startCommand = "docker-compose up -d"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[[services]]
name = "brainbrawler-postgres"
source = "postgres"

[[services]]
name = "brainbrawler-redis" 
source = "redis"

[[services]]
name = "brainbrawler-zookeeper"
source = "zookeeper"

[[services]]
name = "brainbrawler-kafka"
source = "kafka"

[[services]]
name = "brainbrawler-backend"
source = "backend"

[[services]]
name = "brainbrawler-frontend"
source = "frontend"

[environments.production.variables]
NODE_ENV = "production"
KAFKA_ENABLED = "true"
REDIS_ENABLED = "true"
SMTP_ENABLED = "false"
GAME_ENGINE_ENABLED = "true"
SOCKET_IO_ENABLED = "true" 