databases:
  - name: brainbrawler-db
    databaseName: brainbrawler
    user: brainbrawler_user
    plan: free
    region: frankfurt

services:
  # Redis Cache Service
  - type: redis
    name: brainbrawler-redis
    plan: free
    region: frankfurt
    ipAllowList: []
  # Backend API + Socket.io + GameEngine integrato
  - type: web
    name: brainbrawler-api
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy
    startCommand: npm start
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: brainbrawler-db
          property: connectionString
      - key: REDIS_URL
        fromDatabase:
          name: brainbrawler-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://brainbrawler-frontend.onrender.com
      - key: GAME_ENGINE_ENABLED
        value: true
      - key: SOCKET_IO_ENABLED
        value: true
      - key: DEFAULT_QUESTION_TIME
        value: 15
      - key: DEFAULT_TOTAL_QUESTIONS
        value: 5
      - key: MAX_PLAYERS_PER_ROOM
        value: 8
      - key: ROOM_CODE_LENGTH
        value: 6
      - key: AUTO_START_THRESHOLD
        value: 2
      - key: CONNECTION_POOL_SIZE
        value: 5
      - key: REDIS_TTL
        value: 3600
  
  # Frontend statico
  - type: web
    name: brainbrawler-frontend
    env: static
    buildCommand: cd frontend && chmod +x build.sh && ./build.sh
    staticPublishPath: frontend
    envVars:
      - key: REACT_APP_API_URL
        value: https://brainbrawler-api.onrender.com
